# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'
workspace 'MobileTrading'
use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

pod 'libPhoneNumber-iOS'
pod 'RealmSwift'
pod 'SwifterSwift'
pod 'ObjectMapper'
pod 'ReSwift'
pod 'IQKeyboardManagerSwift'
pod 'Moya'
# Cryptor, use CrytoSwift for all encode/decode/hash
pod 'RNCryptor'
pod 'CryptoSwift'
# An extension of Data. It enables compress/decompress gzip using zlib.
pod 'GzipSwift'
pod 'Zip'
pod 'SSZipArchive'
pod 'APNGKit', '~> 0.6'
pod 'CocoaLumberjack'
pod 'CocoaLumberjack/Swift'
pod 'Fashion'
pod 'Reusable'
pod 'Stripe'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
pod 'TYAlertController'
pod 'LGSideMenuController'
pod 'CNPPopupController'
pod 'DZNEmptyDataSet'
pod 'SCLAlertView'
pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'SwiftMessages'
pod 'SnapKit'
pod 'SVPullToRefresh'
pod 'ESPullToRefresh'
pod 'Toast'
pod 'SwiftyJSON'
pod 'MGSwipeTableCell'
pod 'SwiftDate'
pod 'SwiftLocation'
pod 'SwiftLint'

#    pod 'SignalR-ObjC'
#    pod 'Fabric'
#    pod 'Crashlytics'
#    pod 'Cartography'
#    pod 'PromiseKit'
#    pod 'FontasticIcons'

#    pod 'PDTSimpleCalendar'
#    pod 'MagicalRecord'
#    pod 'ChameleonFramework'
#    pod 'TextFieldEffects'
#    pod 'GPUImage'
#    pod 'iRate'
#    pod 'PKRevealController'
#    pod 'SlackTextViewController'
#    pod 'PermissionScope'
#Pusher
#    pod 'PusherSwift'
#    pod 'FontAwesomeKit'

#    pod 'IAPHelper'
#    pod 'RxSwift'
#    pod 'RxCocoa'

#    pod 'FontBlaster'
#    pod 'TAPromotee'
#    pod 'KeychainAccess'
#    pod 'Charts'

#    pod 'Fakery'
#    pod 'Kingfisher'

#    pod 'HTMLAttributedString'

#    pod 'ImageSlideshow/Kingfisher'
#    pod 'DYSlideView'
#    pod 'Segmentio'
#    pod 'PopupDialog'
#    pod 'SCSkypeActivityIndicatorView'

target 'MobileTrading' do
    project 'MobileTrading'

    target 'MobileTradingTests' do
        inherit! :search_paths
        # Pods for testing
        pod 'Quick'
        pod 'Nimble'
        pod 'Nimble-Snapshots'
    end
    
    target 'MobileTradingUITests' do
        inherit! :search_paths
        # Pods for testing
        pod 'Quick'
        pod 'Nimble'
        pod 'Nimble-Snapshots'
    end
    
    target 'GzipTests' do
        inherit! :search_paths
        # An extension of Data. It enables compress/decompress gzip using zlib.
        pod 'GzipSwift'
    end
    
    target 'CryptoSwiftTests' do
        inherit! :search_paths
        pod 'CryptoSwift'
    end
    
    target 'RNCryptorTests' do
        inherit! :search_paths
        pod 'RNCryptor'
    end
    
    target 'ZipTests' do
        inherit! :search_paths
        pod 'Zip'
    end
    
    target 'SSZipArchiveTests' do
        inherit! :search_paths
        pod 'SSZipArchive'
    end
    
    target 'APNGKitTests' do
        inherit! :search_paths
        pod 'APNGKit', '~> 0.6'
    end
    
    target 'NimbleTests' do
        inherit! :search_paths
        pod 'Quick'
        pod 'Nimble'
        pod 'Nimble-Snapshots'
    end
    
    target 'QuickTests' do
        inherit! :search_paths
        pod 'Quick'
        pod 'Nimble'
        pod 'Nimble-Snapshots'
    end
    
    target 'LibPhoneNumberTests' do
        inherit! :search_paths
        pod 'libPhoneNumber-iOS'
    end
    
    target 'SwifterSwiftTests' do
        inherit! :search_paths
        pod 'SwifterSwift'
    end
    
end

target 'LGKKCoreLib' do
    project '../LGKKCoreLib/LGKKCoreLib'
    
    target 'LGKKCoreLibTests' do
        inherit! :search_paths
        pod 'Quick'
        pod 'Nimble'
        pod 'Nimble-Snapshots'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.1'
            config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
    end
end
